[package]
name = "pandorusttasks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.2.0"
reqwest = "0.11.18"
tokio = { version = "1.29.1", features = ["full"] }
serde_json = "1.0.99"
